export default {
    greeting: "Hey!\nHow are you?",
    description: "You're in a safe space where no one will judge you.\nTell us what's on your mind — we're here to listen and help.",
    next: "CONTINUE",
    greeting_form: "Describe your mood, \nthoughts or worries",
    description_form: "I'll analyze your condition and give helpful advice",
    submit: "SUBMIT",
    placeholder: "How are you?",
    alert_empty_title: "Empty Input",
    alert_empty_message: "Please write something before submitting.",
    alert_success_title: "Submitted!",
    log_in: "Log In",
    sign_in: "Sign In",
    email: "Email",
    password: "Password",
    login: "Login",
    invalid_email_or_password: "I'm sorry, but you entered an incorrect email or password",
    enter_email: "Enter your Email",
    create_account: "Create Account",
    name: "Name",
    continue: "Continue",
    register: "Register",
    error_checking_email: "Error checking email. Try again.",
    error_registering: "Error creating account. Try again.",
    choose_sex: "Sex",
    male: "male",
    female: "female",
    other: "other",
    enter_password: "Please, enter password",
    forgot_password: "forgot password?"
  };
  