export default {
  greeting: "Hello!",
  greeting_question: "How are you today?",
  description: "You’re in a safe space where no one will judge you.\nTell us what's on your mind — we’re here to listen and help.",
  greeting_form: "Describe your mood, \nthoughts or worries",
  description_form: "I’ll analyze your state and give tips that might help",
  submit: "DONE",
  placeholder: "How are you?",
  alert_empty_title: "Empty field",
  alert_empty_message: "Please write something before submitting.",
  alert_success_title: "Submitted!",
  log_in: "Log in",
  sign_in: "Sign in",
  email: "Email",
  password: "Password",
  login: "Log in",
  invalid_email_or_password: "Sorry, the email or password you entered is incorrect",
  enter_email: "Enter your email to continue",
  create_account: "Create an account",
  name: "Name",
  continue: "Continue",
  register: "Register",
  error_checking_email: "Error checking email. Please try again.",
  error_registering: "Error creating account. Please try again.",
  choose_sex: "Sex",
  male: "Female",
  female: "Male",
  other: "Other",
  enter_password: "Please enter your password",
  forgot_password: "Forgot password?",
  invalid_email: "Oops, invalid email format. Try again.",
  we_are_happy_register: "We’re so happy you decided to join us",
  we_are_happy: "Make your experience with us more personalized",
  welcome_back: "Happy to see you again!",
  wrong_password: "Oops, wrong password. Please try again",
  google: "or \n Sign in with Google",
  forgot_password_title: "Forgot Password",
  enter_your_email: "Enter your email to reset your password",
  send_reset_link: "Send Reset Link",
  old_password:"Old password",
  new_password:"New password",
  reset_link_sent: "Check your email for the reset link!",
  error_sending_link: "Failed to send the link. Please try again.",
  friend: "friend",
  welcome: "Welcome",
  edit_your_data: "Do you want to edit your data?",
  or_view: "Or view",
  diary: "Diary",
  logout: "Logout",
  change_language: "or change language",
  confirm: "Confirm"
};
