export default {
    greeting: "Привіт!",
    greeting_question: "Як ти сьогодні?",
    description: "Ти в безпечному просторі, де тебе ніхто не осудить.\nРозкажи, що в тебе на думці — ми тут, щоб вислухати й допомогти.",
    greeting_form: "Опиши свій настрій, \nдумки чи тривоги",
    description_form: "Я проаналізую твій стан і дам поради, що можуть стати у пригоді",
    submit: "ГОТОВО",
    placeholder: "Як ти?",
    alert_empty_title: "Пусте поле",
    alert_empty_message: "Будь ласка, напиши щось перед відправкою.",
    alert_success_title: "Відправлено!",
    log_in: "Увійти",
    sign_in: "Вхід",
    email: "Пошта",
    password: "Пароль",
    login: "Увійти",
    invalid_email_or_password: "Мені прикро, але ви ввели неправильниу пошту або пароль",
    enter_email: "Введіть пошту, щоб продовжити",
    create_account: "Створити акаунт",
    name: "Ім'я",
    continue: "Продовжити",
    register: "Зареєструватися",
    error_checking_email: "Помилка перевірки пошти. Спробуйте ще раз.",
    error_registering: "Помилка створення акаунту. Спробуйте ще раз.",
    choose_sex: "Стать",
    male: "Жінка",
    female: "Чоловік",
    other: "Інше",
    enter_password: "будь ласка, введіть ваш пароль",
    forgot_password: "забули пароль?",
    invalid_email: "Упс, некоректний формат пошти. Спробуйте ще раз" ,
    we_are_happy_register: "Ми дуже раді, що ви вирішили до нас приєднатися",
    we_are_happy: "Зробіть свій досвід з нами більш персоналізованим",
    welcome_back:"Раді бачити вас знову!",
    wrong_password: "Упс, неправильний пароль. Спробуйте ще раз"
  };
  